surface.CreateFont("GPS::MenuFont", {
    font = "Tahoma",
    extended = false,
    size = math.Clamp(ScrH() * (25/1080),8,255),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
})

surface.CreateFont("GPS::DermaLarge", { -- we want it to scale,  yes?
    font = "Roboto",
    extended = false,
    size = math.Clamp(ScrH() * (32/1080),8,255),
    weight = 500,
    blursize = 0,
    scanlines = 0,
    antialias = true,
    underline = false,
    italic = false,
    strikeout = false,
    symbol = false,
    rotary = false,
    shadow = false,
    additive = false,
    outline = false,
})